# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# WordPress Template - Docker Compose
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━^

services:
  mysql:
    build:
      context: .
      dockerfile: images/mysql/Dockerfile
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - wordpress_net

  wordpress:
    build:
      context: .
      dockerfile: images/wordpress/Dockerfile
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
    container_name: ${PROJECT_NAME}_wordpress
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      WORDPRESS_VERSION: ${WORDPRESS_VERSION}
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - '9000:9000'
    networks:
      - wordpress_net

networks:
  wordpress_net:
    driver: bridge
